blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/cmdscale/CmdScale.EntityFrameworkCore.TimescaleDB/issues
    about: For general questions, open a discussion or browse existing issues.
